### ISSUE TITLE
Connect CosmoSDB with the New user

### ISSUE THREAD

**Issue by atulec016** [PlagueHO/CosmosDB#100]
Hello Team ,

I have successfully created the new user for the COsmos DB .Could you please let me know how to use the use to connect to the Cosmos DB using 3T or any way to connect via this user

Thanks
Atul Gupta

**Comment by PlagueHO** [comment]
Hi @atulec016 - you don't actually connect via a user to CosmosDB. Rather you need to create a user, then assign permissions to that user granting them access to specific resources (e.g. a Collection or a Document).

You can then use the Get-CosmosDBPermission function to get the permissions assigned to the user. This allows you to use a Resource key to retrieve the resource rather than the master key.

However, I haven't actually completed this functionallity (or at least tested it). This actually relates to this issue: https://github.com/PlagueHO/CosmosDB/issues/33

I'm planning on completing this over the next week. At which time I'll cover the usage in the README.MD.

**Comment by PlagueHO** [comment]
Hi @atulec016 - I've made the necessary changes and produced some basic example documentation on how to use User Resource Tokens to gain access to resources: https://github.com/PlagueHO/CosmosDB#using-resource-authorization-tokens

You'll need at least Cosmos DB Module 2.0.12 to make use of this.

But the is really not that much use without an external Authentication provider (token broker) that validates credentials of a user and returns Resource Tokens. See the links in the documentation I've added.

HTH

**Comment by atulec016** [comment]
Hello Dan ,

Thanks for the details here :)

My next concern would be why cant we see any users in the Studio 3T while
connecting to the Cosmos DB (Mongo Api). I want to restrict the user from
accessing through the GUI.
Is there any way that would help to create and restrict the user to
particular collection or database?


Regards,
Atul Gupta

**Comment by PlagueHO** [comment]
Hi @atulec016 - I'm not actually familiar with the Studio 3T product (I know what it is and that is about it). I'm also not much of an expert on the Mongo DB API as I always use the SQL API.

I actually have no idea if you can restrict access to collections/documents/databases in the Studio 3T by using users/permissions. The users/permissions are essentially just collections themselves and don't provide authentication or authorization.

So you might need a slightly different approach for Mongo DB API. Sorry I can't offer more help but I'm really not an expert in how Cosmos DB implements the Mongo DB API and whether or not Mongo DB API even implements an authentication layer.

The REST API that this PowerShell module actually uses doesn't provide an authentication layer either. The master or resource keys are used to validate each request to the REST API, but as long as you've got master key for the Account or a resource key for the resource you want to access then there is no other authorization/authentication (per se).

Does that help at all?

**Comment by atulec016** [comment]
Hello Dan,

Thanks for all your suggestions so far:) its really been a great help.

Yes, I am also not sure "How the Authentication layer works in the Cosmos DB Mongo API" .We have the Keys and account name to access the DB but we cant give this Admin rights to all the users because of that i was trying to create a separate user to restrict the access to read only.
That's where i am stuck now.

Thanks.
Atul Gupta

**Comment by PlagueHO** [comment]
@atulec016 - In Cosmos DB with SQL API the only way to restrict access to resources by a specific user is to use the "Token Broker" pattern where you create an intermediary App that provides authentication. The intermediary Token Broker holds the "master keys" and uses them to create and distribute resource level keys (essentially SAS tokens) to users who have successfully authenticated. There really isn't another way of doing this using the SQL API that I know of - Mongo DB API might be different, but I'd be surprised. It is possible the Mongo DB API has implemented an additional authentication layer though - but I just don't know enough about it.
