### ISSUE TITLE
Add Support for Database Throughput Provisioning

### ISSUE THREAD

**Issue by PlagueHO** [PlagueHO/CosmosDB#110]
Azure Cosmos DB now supports sharing reserved throughput across multiple collections in a database:
https://docs.microsoft.com/en-us/azure/cosmos-db/set-throughput#provision-throughput-for-a-set-of-containers-or-at-the-database-level

This is not yet documented in the REST APIs:
https://docs.microsoft.com/en-us/rest/api/cosmos-db/create-a-database

When this is documented/available support should be added.

**Comment by smneal** [comment]
I have just been looking at this and wondered whether there is support here. The portal request for this includes an additional header "x-ms-offer-throughput: 50000".

**Comment by PlagueHO** [comment]
Oh right - so it looks to use the same header as the new collection does? If that is the case then it should be easy enough to add. I'd assume the lower & upper limits are the same as in the portal.

**Comment by lanndoc** [comment]
I could really use this functionality soon.

**Comment by PlagueHO** [comment]
Thanks for reminding me about this one @lanndoc - I'll see if I can get it done over the weekend.

**Comment by PlagueHO** [comment]
Onto this now @lanndoc

**Comment by PlagueHO** [comment]
This has now been published to PSGallery @lanndoc and @smneal as 3.4.0.411: https://www.powershellgallery.com/packages/CosmosDB/3.4.0.411
