### ISSUE TITLE
Update Spacial to Spatial

### ISSUE THREAD

**Issue by smneal** [PlagueHO/CosmosDB#112]
https://github.com/PlagueHO/CosmosDB/blob/00175d75ae4cda90ba7db1735305253739841bd5/src/lib/collections.ps1#L62

Received the following response when trying to create this kind of index:

"The specified index type value 'Spacial' is invalid. Please choose among 'Hash', 'Range', and 'Spatial' index types."

**Comment by PlagueHO** [comment]
Thanks for raising this @smneal - definitely looks like a bug to me. I'll get it sorted today/tomorrow.

**Comment by PlagueHO** [comment]
I've fixed this and am just preparing the release. I also added some better parameter validation to the function to prevent invalid DataType/Kind combinations.

**Comment by PlagueHO** [comment]
This fix has been released to PSGallery now.
