### ISSUE TITLE
Unable to create Spatial index

### ISSUE THREAD

**Issue by smneal** [PlagueHO/CosmosDB#115]
When I try to create an included path which contains a spatial index the request fails because the precision property is always returned from New-CosmosDbCollectionIncludedPathIndex whether I specify it or not. The error returned is "The 'Spatial' index type should not have a precision specified."

**Comment by PlagueHO** [comment]
Thanks for raising this. I need to extend the integration testing to cover some more of these scenarios to pick this up. I'll resolve this tonight.

**Comment by PlagueHO** [comment]
I've corrected this now in Dev and I'll publish to the PS Gallery after this issue is also merged: https://github.com/PlagueHO/CosmosDB/pull/117

Feel free to use Dev branch until this is released to the PSGallery (which I'm hoping will be tomorrow).

**Comment by smneal** [comment]
Many thanks for sorting this.

**Comment by PlagueHO** [comment]
@smneal - no problem at all! This has been published to the PS Gallery now. Hopefully this will resolve the issue now.
