### ISSUE TITLE
Stored Procedure Invoke Enhancements

### ISSUE THREAD

**Issue by jasonchester** [PlagueHO/CosmosDB#116]
While testing out a  performing complicated aggregations in cosmosdb using stored procs (https://github.com/lmaccherone/documentdb-lumenize) I ran smack into some limitations of the stored proc Implementation.

In order to address the limitations **Invoke-CosmosDbStoredProcedure** should
- Support for specifying -PartitionKey 
-- this is required when executing a stored procedure in a partitioned collection
- Change StoredProcedureParameters from string[] to object[]
-- Should be able to handle most cases with ConvertTo-Json
- Add -EnableScriptDebugging parameter when executing a stored procedure
-- This appears to be missing from rest api documentation
-- Relevant SO https://stackoverflow.com/questions/47855094/how-to-debug-azure-cosmos-db-stored-procedures
-- Consider adding this to the cosmos request automatically when Powershell -Debug is used. 

Planning to put together a PR for these if time allows.

**Comment by PlagueHO** [comment]
This has now been merged. I'll release to the PS Gallery later on tonight.

**Comment by PlagueHO** [comment]
Thanks again for contributing @jasonchester !

**Comment by PlagueHO** [comment]
This has been published to the PS Gallery now.
