### ISSUE TITLE
Add support for setting the Collection DefaultTTL value

### ISSUE THREAD

**Issue by smneal** [PlagueHO/CosmosDB#139]
On the Azure Portal it is possible to set the default "Time to live" value on a collection. This can be implemented relatively easily be passing the DefaultTtl value when creating or updating a collection.

Allowable values:
Excluding the value (or setting it to NULL) - Off;
Setting this to -1 which means infinite;
Setting this to a value in seconds e.g. 2592000 for 30 days.

Docs: https://docs.microsoft.com/en-us/azure/cosmos-db/time-to-live#ttl-behavior

**Comment by PlagueHO** [comment]
Thanks for raising this @smneal - looks like it'll be easy to add. Will get onto this over the weekend.

**Comment by PlagueHO** [comment]
Released to gallery in https://www.powershellgallery.com/packages/CosmosDB/2.1.3.528

**Comment by smneal** [comment]
Many thanks for updating this so quickly!
