### ISSUE TITLE
New-CosmosDbCollection / Set-CosmosDbCollection Indexing Policy inconsistency

### ISSUE THREAD

**Issue by EwanNoble** [PlagueHO/CosmosDB#140]
- [ ] Version of PowerShell you're using
5.1
- [ ] PowerShell host you're using (eg. Console Host, ISE, Visual Studio)
VS Code
- [ ] Operating system you're running
Win 10
- [ ] Version of CosmosDB you're using (use `Get-Module -Name CosmosDB`)
2.1.2.514

The IndexingPolicy parameter on the API for Creating and Updating a cosmos Db collection is optional on both. 
https://docs.microsoft.com/en-us/rest/api/cosmos-db/replace-a-collection#request

The New-CosmosDbCollection cmdlet has IndexingPolicy as an optional parameter:
https://github.com/PlagueHO/CosmosDB/blob/master/src/lib/collections.ps1#L390-L393

The Set-CosmosDbCollection cmdlet has IndexingPolicy as mandatory:
https://github.com/PlagueHO/CosmosDB/blob/master/src/lib/collections.ps1#L548-L551

These should be aligned

**Comment by PlagueHO** [comment]
Thanks for raising this @EwanNoble - I'll get onto this tonight.

**Comment by PlagueHO** [comment]
Released to gallery in https://www.powershellgallery.com/packages/CosmosDB/2.1.3.528

**Comment by EwanNoble** [comment]
Many thanks @PlagueHO !
