### ISSUE TITLE
Unable to turn off DefaultTtl if it is already set

### ISSUE THREAD

**Issue by smneal** [PlagueHO/CosmosDB#144]
When updating a collection where the DefaultTtl is already set it is not possible to turn it off. When calling Set-CosmosDbCollection it will always take the existing value even if the parameter is not included.

Valid values for DefaultTtl include not specifying it at all or NULL.

I think removing the following lines should fix it:
https://github.com/PlagueHO/CosmosDB/blob/992454c7a8904b4b3e091443043d23a71fd3c418/src/lib/collections.ps1#L619-L624

**Comment by PlagueHO** [comment]
What I've done is add a switch parameter `RemoveDefaultTimeToLive` to the function to allow removal of the default TTL. The reason for doing this is that you may want to be able to reconfigure the index on a collection without specifically changing the DefaultTimeToLive value on it (e.g. just leaving it set as is).

**Comment by PlagueHO** [comment]
This has been released to the PS Gallery: https://www.powershellgallery.com/packages/CosmosDB/2.1.4.536

**Comment by smneal** [comment]
Many thanks again!
