### ISSUE TITLE
New-CosmosDbContext - support full URL to host.

### ISSUE THREAD

**Issue by davidwmartines** [PlagueHO/CosmosDB#155]
When creating a context, can we just specify the full url and key?   This would be handy when using the Emulator that is not listening on localhost and/or uses a custom key.  For example when starting the emulator with the `/AllowNetworkAccess` and `/Key` options.

**Comment by PlagueHO** [comment]
Hi @davidwmartines - I think this should be easy enough to implement. I'll take a look this weekend.

**Comment by PlagueHO** [comment]
I've finished this off now and will get it published to the PS Gallery in the next hour.

**Comment by PlagueHO** [comment]
@davidwmartines - this has been released to PS Gallery: https://www.powershellgallery.com/packages/CosmosDB/2.1.6.561

See examples here:
https://github.com/PlagueHO/CosmosDB#create-a-context-for-a-cosmos-db-emulator
