### ISSUE TITLE
Unique keys

### ISSUE THREAD

**Issue by tlanda** [PlagueHO/CosmosDB#197]
Would you consider to support creating Collections with with a unique key policy? 
https://docs.microsoft.com/en-us/azure/cosmos-db/unique-keys

**Comment by PlagueHO** [comment]
Update: I got some great info from the Cosmos DB team and MVPs. To create a unique policy we must add the following into the collection body:
```json
"uniqueKeyPolicy": {
    "uniqueKeys": [
      { "paths": [ "/name", "/address "] },
      { "paths": [ "/email" ] }
    ]
  }
```

**Comment by PlagueHO** [comment]
@tlanda - I've finished work on this and am just finishing up the integration tests on this now. I'll have this out in the next release later on this week.

**Comment by tlanda** [comment]
Great, thank you very much!

**Comment by PlagueHO** [comment]
A pleasure! Just releasing this to the PSGallery now as 2.1.12. Check there tomorrow.

**Comment by PlagueHO** [comment]
Published to gallery here: https://www.powershellgallery.com/packages/CosmosDB/2.1.12.137

Documentation on how to use it in the Wiki: https://github.com/PlagueHO/CosmosDB/wiki#creating-a-collection-with-a-custom-unique-key-policy
