### ISSUE TITLE
400 Bad Request when using -Query

### ISSUE THREAD

**Issue by divgo** [PlagueHO/CosmosDB#22]
- [ ] Version of PowerShell you're using: 5.1.14393.1770
- [ ] PowerShell host you're using: ISE
- [ ] Operating system you're running: Windows 10
- [ ] Version of CosmosDB: 1.0.10.108

Issuing the following command;
```
$params = @(@{name = "@in_newrelic";value="false";})
$documents = Get-CosmosDbDocument -Database devops -Connection $Connection -CollectionId 'inventory' -Query "SELECT * FROM inventory WHERE (inventory.in_newrelic = @in_newrelic)" -QueryParameters $params
```

returns the following response;
```
Invoke-WebRequest : The remote server returned an error: (400) Bad Request.
At C:\Program Files\WindowsPowerShell\Modules\CosmosDB\1.0.10.108\lib\utils.ps1:477 char:23
+ ... estResult = Invoke-WebRequest -UseBasicParsing @invokeRestMethodParam ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (System.Net.HttpWebRequest:HttpWebRequest) [Invoke-WebRequest], WebException
    + FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeWebRequestCommand
 
ConvertFrom-Json : Cannot bind argument to parameter 'InputObject' because it is null.
At C:\Program Files\WindowsPowerShell\Modules\CosmosDB\1.0.10.108\lib\documents.ps1:294 char:54
+         $tempObject = (ConvertFrom-JSON -InputObject $result.Content)
+                                                      ~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidData: (:) [ConvertFrom-Json], ParameterBindingValidationException
    + FullyQualifiedErrorId : ParameterArgumentValidationErrorNullNotAllowed,Microsoft.PowerShell.Commands.ConvertFromJsonCommand
```

When I run the following,
```
$Query = "select * from inventory where (in_newrelic = @in_newrelic)"
$QueryParameters = @(@{name = "@in_newrelic";value="false";}) # @(@{name = "@in_newrelic";value = "false"})

**$bodyObject = @{ query = $Query }
if (-not [String]::IsNullOrEmpty($QueryParameters))
{
    $bodyObject += @{ parameters = $QueryParameters }
}
ConvertTo-Json -InputObject $bodyObject**
```
the output JSON object appears to match the desired format according to the CosmosDB RestAPI documentation.
```
{
    "query":  "select * from inventory where (in_newrelic = @in_newrelic)",
    "parameters":  [
                       {
                           "value":  "false",
                           "name":  "@in_newrelic"
                       }
                   ]
}
```

The bold portion of the script was taken from the source code. I wanted to ensure that the resulting body passed to the RestAPI was in the desired format, which it is. I also checked and the source code seems to be setting the "x-ms-documentdb-isquery" header, so I cannot tell what else could be wrong here.
I can return documents from the table using the following command;
`$documents = Get-CosmosDbDocument -Database devops -Connection $Connection -CollectionId 'inventory' -MaxItemCount 5`

**Comment by divgo** [comment]
It looks like the problem might be on line 460 of /lib/utils.ps1
        ContentType = 'application/json'

The ContentType is being reset to application/json rather than application/query+json

I also didnt notice Content-Length being set on a POST method, though I am unsure if that is really a problem.

**Comment by PlagueHO** [comment]
Great feedback and info @divgo ! Looks like you could be right. I'll get this fixed tonight! Really good catch and thanks for raising this.

**Comment by PlagueHO** [comment]
Hi @divgo - your summation was quite correct. I was overriding the content-type header. I've resolved the issue and releasing it now. I've also added the documentation for Querying to the README.MD.

**Comment by divgo** [comment]
Hi Daniel,

Thank you for your kind words. I am glad I could help and impressed by your rapid turnaround on this issue. Kudos as well for updating the documentation!

**Comment by PlagueHO** [comment]
A pleasure @divgo - thank you. Feel free to raise any further issues and I'll address them as quickly as possible.
