### ISSUE TITLE
Get-CosmosDbCollection checking if collection exists - endless loop

### ISSUE THREAD

**Issue by lukeb1961** [PlagueHO/CosmosDB#240]
I expected it to return null. Instead it goes loop forever...

Get-CosmosDbCollection -Context $cosmosCTX -id 'nosuchcoll'
VERBOSE: GET https://lukeb-cosmosdbacc.documents.azure.com/dbs/CosmosTestDB/colls/nosuchcoll with 0-byte payload
Unable to find type [Microsoft.PowerShell.Commands.HttpResponseException].
At C:\Program Files\WindowsPowerShell\Modules\CosmosDB\2.1.8.59\lib\utils.ps1:566 char:41
+ ... t.WebException],[Microsoft.PowerShell.Commands.HttpResponseException]
+                     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (Microsoft.Power...sponseException:TypeName) [], RuntimeException
    + FullyQualifiedErrorId : TypeNotFound
 
VERBOSE: GET https://lukeb-cosmosdbacc.documents.azure.com/dbs/CosmosTestDB/colls/nosuchcoll with 0-byte payload
Unable to find type [Microsoft.PowerShell.Commands.HttpResponseException].
At C:\Program Files\WindowsPowerShell\Modules\CosmosDB\2.1.8.59\lib\utils.ps1:566 char:41
+ ... t.WebException],[Microsoft.PowerShell.Commands.HttpResponseException]
+                     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (Microsoft.Power...sponseException:TypeName) [], RuntimeException
    + FullyQualifiedErrorId : TypeNotFound
 
VERBOSE: GET https://lukeb-cosmosdbacc.documents.azure.com/dbs/CosmosTestDB/colls/nosuchcoll with 0-byte payload
Unable to find type [Microsoft.PowerShell.Commands.HttpResponseException].
At C:\Program Files\WindowsPowerShell\Modules\CosmosDB\2.1.8.59\lib\utils.ps1:566 char:41
+ ... t.WebException],[Microsoft.PowerShell.Commands.HttpResponseException]
+                     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (Microsoft.Power...sponseException:TypeName) [], RuntimeException
    + FullyQualifiedErrorId : TypeNotFound
 
VERBOSE: GET https://lukeb-cosmosdbacc.documents.azure.com/dbs/CosmosTestDB/colls/nosuchcoll with 0-byte payload
Unable to find type [Microsoft.PowerShell.Commands.HttpResponseException].
At C:\Program Files\WindowsPowerShell\Modules\CosmosDB\2.1.8.59\lib\utils.ps1:566 char:41
+ ... t.WebException],[Microsoft.PowerShell.Commands.HttpResponseException]
+                     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (Microsoft.Power...sponseException:TypeName) [], RuntimeException
    + FullyQualifiedErrorId : TypeNotFound

PS C:\WINDOWS\system32> $PSVersionTable
Name                           Value                                                                                        
----                           -----                                                                                        
PSVersion                      5.1.17763.1                                                                                  
PSEdition                      Desktop                                                                                      
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                      
BuildVersion                   10.0.17763.1                                                                                 
CLRVersion                     4.0.30319.42000                                                                              
WSManStackVersion              3.0                                                                                          
PSRemotingProtocolVersion      2.3                                                                                          
SerializationVersion           1.1.0.1

**Comment by PlagueHO** [comment]
Hi @lukeb1961 - I suspect this is related to this issue here: https://github.com/PlagueHO/CosmosDB/issues/186

This was released to the PS Gallery in 2.1.9:
https://github.com/PlagueHO/CosmosDB/pull/191

So if you update to 2.1.9 or above this should be fixed (hopefully :grin: - if it isn't please let me know!)

**Comment by PlagueHO** [comment]
I think this one has been resolved. I'll close it. If this is still an issue @lukeb1961, please feel free to reopen it.
