### ISSUE TITLE
Parameter Validation on New-CosmosDbContext -Account cannot handle legacy database accounts with names > 31 characters

### ISSUE THREAD

**Issue by cpdohert** [PlagueHO/CosmosDB#241]
- [5.1.17134.228] Version of PowerShell you're using
- [ISE] PowerShell host you're using (eg. Console Host, ISE, Visual Studio)
- [Windows 10 1803] Operating system you're running
- [2.1.13.215] Version of CosmosDB PowerShell Module you're using

"New-CosmosDbContext : Cannot validate argument on parameter 'Account'. The Account Name 'xxxxxxxx-xxxxxx-xxxxxxx-pub-cdba' is invalid. The name can contain only lowercase letters, 
numbers and the '-' character, and must be between 3 and 31 characters."

The previous Azure limit was 50 characters and we have accounts that were created at that time that we can no longer interact with using the CosmosDB module.

**Comment by PlagueHO** [comment]
Hi @cpdohert - ah, right. Sorry about that. I implemented the limit based off the information provided in the Portal:
![image](https://user-images.githubusercontent.com/7589164/48516343-02a0dc80-e8c8-11e8-80c3-7e6a8d1f79fb.png)

It looks like there is some inconsistency with the portal and "reality" :cry:

I'll get an emergency release out to extend the limit to 50 chars.

**Comment by cpdohert** [comment]
The Azure Team doesn't seem to have advertised this breaking change anywhere and we only tripped across it today.  We heavily rely on the CosmosDb module for managing our app and we appreciate your fast response.  Thanks!

**Comment by PlagueHO** [comment]
No worries at all! I'll raise this inconsistency with the Cosmos DB team and see if they can update the portal.

The new version should be up on the gallery in a couple of hours - just waiting for tests to complete.

**Comment by PlagueHO** [comment]
I'll post in this issue when the new version is on the gallery. Should be in about an hour.

**Comment by PlagueHO** [comment]
The new version is out on the PS Gallery now: https://www.powershellgallery.com/packages/CosmosDB/2.1.14.222
