### ISSUE TITLE
Get-CosmosDbCollection does not return all collections

### ISSUE THREAD

**Issue by Ponomareff** [PlagueHO/CosmosDB#244]
ConsoleHost: 5.1.16299.666
CosmosDb: 2.1.13.215

Get-CosmosDbCollection -Context $context -Database 'Database' | Measure-Object
Always returns Count: 100 for database with more than 100 collections.

Observed:
Invoke-CosmosDbRequest does not honor continuation token (x-ms-continuation) and returns only first page of data, limiting results to 100 records.

Expected:
Calls Invoke-WebRequest until all results are returned

**Comment by PlagueHO** [comment]
Hi @Ponomareff - Thank you - that is great feedback. The documentation didn't mention support for the x-ms-continuation token (https://docs.microsoft.com/en-us/rest/api/cosmos-db/list-collections) but this does make complete sense. I suspect the same would be for users, permissions, stored procedures, user defined functions, triggers and attachments.

But I'll start with implementing this. Thanks for pointing this out.

**Comment by PlagueHO** [comment]
I've finished the change to enable this and will release it shortly.

**Comment by Ponomareff** [comment]
> I've finished the change to enable this and will release it shortly.

Thank you so much, Daniel. It was very fast. Excellent support!

**Comment by PlagueHO** [comment]
My pleasure @Ponomareff - this has now been published to the PS Gallery as 2.1.15.239: https://www.powershellgallery.com/packages/CosmosDB/2.1.15.239
