### ISSUE TITLE
New-CosmosDbAttachment -PartitionKey support

### ISSUE THREAD

**Issue by ruipach** [PlagueHO/CosmosDB#274]
# Issue

**[New-CosmosDbAttachment](https://github.com/PlagueHO/CosmosDB/wiki/New-CosmosDbAttachment)** does not support PartitionKey for latest API version, HTTP 400 without it.

- [ ] Microsoft.Azure.Documents.Common/2.1.0.0
- [ ] $PSVersionTable.PSVersion

```
Major  Minor  Build  Revision
-----  -----  -----  --------
5      1      16299  820
```

- [ ] Windows Powershell ISE
- [ ] Windows 10 Enterprise
- [ ] Get-Module -Name CosmosDB

```
ModuleType Version    Name                                ExportedCommands                                                                                                                
---------- -------    ----                                ----------------                                                                                                                
Script     3.1.0.293  CosmosDB                            {Get-CosmosDbAccount, Get-CosmosDbAccountConnectionString, Get-CosmosDbAccountMasterKey, Get-CosmosDbAttachment...} 
```

**Comment by PlagueHO** [comment]
Thanks for raising this @ruipach - I'll get onto looking at this tonight

**Comment by PlagueHO** [comment]
I have managed to replicate this now. Unfortunately the REST API documentation hasn't been updated yet, so I'm going to need to go blind on this one: https://docs.microsoft.com/en-us/rest/api/cosmos-db/create-an-attachment

**Comment by PlagueHO** [comment]
I've completed the support for this and I'll try and have this in the PS Gallery for you by tomorrow.

**Comment by ruipach** [comment]
Hi Daniel
Sorry to bother you, just a warning about the documentation.
The SYNTAX Context(default) does not mention the PartitionKey support, shouldn't it?

**Comment by PlagueHO** [comment]
Hi @ruipach - no bother at all!

That is good info!

Could you clarify what you mean by the SYNTAX Context(default)?

The strange thing about the PartitionKey when creating a collection is that it doesn't seem to YET be mandatory (I have even got integration tests that validate this: https://github.com/PlagueHO/CosmosDB/blob/dev/test/Integration/CosmosDB.integration.Tests.ps1#L514). The REST API docs also refer to this as optional: https://docs.microsoft.com/en-us/rest/api/cosmos-db/create-a-collection

However, this might be a change that hasn't yet made it through all the docs. So I'll reach out to the CosmosDB team and point out the conflicting info and see if I can get them to clear it up one way or another.

If the PartitionKey does become mandatory I'd need to make a breaking change (which I hate doing). Using a default PartitionKey might be risky.

I'll raise a separate issue here in GH to track the issue.

**Comment by PlagueHO** [comment]
Hi @ruipach - I've done a bit more digging and it does look like PartitionKey will be required in the portal. It is mentioned that you can still create collections without PartitionKeys for now via the SDK (which uses the REST APIs like I do).

![image](https://user-images.githubusercontent.com/7589164/53263653-f0dc9a00-373e-11e9-96b3-390d9745900b.png)

So I suspect this may become completely mandatory in future and I've raised an issue to track it:
https://github.com/PowerShell/StorageDsc/issues/181

Finally: I've released the new version of CosmosDB to PSGallery:
https://www.powershellgallery.com/packages/CosmosDB/3.2.1.332

**Comment by ruipach** [comment]
Hi Daniel,

I was mentioning the reference to [-PartitionKey <String[]>] in documentation:
https://github.com/PlagueHO/CosmosDB/wiki/New-CosmosDbAttachment#context-default

Thanks a lot!

**Comment by PlagueHO** [comment]
Ah right! Cool! I've updating the Wiki now so should be good to go :grin: I've asked the Cosmos DB team how they'd normally communicate change.
