### ISSUE TITLE
Encoding error using Get-CosmosDbDocument

### ISSUE THREAD

**Issue by runeemde** [PlagueHO/CosmosDB#282]
Hi,

I'm using special characters and have no problem saving them to the cosmos database using UTF-8 encoding.

`New-CosmosDbDocument -Context $cosmosDbContext -Database $databaseId -CollectionId $collectionId -DocumentBody $documentStr -Encoding UTF-8`

When the data are retrieved again the data is not UTF-8 any more.

`Get-CosmosDbDocument -Context $cosmosDbContext -Database $databaseId -CollectionId $collectionId -Id $documentId`

**Comment by PlagueHO** [comment]
Hi @runeemde - thank you for raising this. I thought I had tests covering this, but I only have them checking if the ID is UTF-8 (https://github.com/PlagueHO/CosmosDB/blob/dev/test/Integration/CosmosDB.integration.Tests.ps1#L1073) - it doesn't check the body. Are you able to paste a sample payload here (with no sensitive data) and I'll use it as a test case to prepare a fix against. I'll take a look at this tonight.

**Comment by runeemde** [comment]
Hi @PlagueHO, Thank you for the quick response.

The picture below shows my cosmos document with a property data "sdsføæå" 
![image](https://user-images.githubusercontent.com/5399017/55503458-fdfa7c00-564e-11e9-9057-a763f059a0ad.png)

And when I'm fetching the data I looks like this
![image](https://user-images.githubusercontent.com/5399017/55503952-0a330900-5650-11e9-9d57-f22bbefb2b76.png)

**Comment by PlagueHO** [comment]
Awesome! Thanks @runeemde. I'll take a look tonight and get it sorted for you.

**Comment by PlagueHO** [comment]
Hi @runeemde - I've found and fixed the problem. It was actually caused by a really old PowerShell issue: https://windowsserver.uservoice.com/forums/301869-powershell/suggestions/13685217-invoke-restmethod-and-invoke-webrequest-encoding-b

I've just got a bit of clean up/refactoring to do to correct it, but I'm aiming to have this out tomorrow for you.

**Comment by runeemde** [comment]
Thanks for quick response @PlagueHO, looking forward to the update!

**Comment by PlagueHO** [comment]
I have submitted a PR to fix this and I'll merge it tomorrow if all the tests pass:
https://github.com/PlagueHO/CosmosDB/pull/283

**Comment by PlagueHO** [comment]
Just releasing this now. Should be out in a few hours.

**Comment by PlagueHO** [comment]
It has been released to the PS Gallery: https://www.powershellgallery.com/packages/CosmosDB/3.2.3.359

**Comment by runeemde** [comment]
Thank you for your quick response, I've testet it with my issue and everything worked great. 

Thanks a million, have a great weekend!

**Comment by PlagueHO** [comment]
My pleasure @runeemde - glad to help :grin:
