### ISSUE TITLE
WARNING: The Get-CosmosDbAccountConnectionString function does not currently work due to an issue with the Microsoft/DocumentDB provider. The connection strings will not be returned

### ISSUE THREAD

**Issue by TimTang** [PlagueHO/CosmosDB#307]
# Issue

with below command:
`Get-CosmosDbAccountConnectionString [-Name] <String> [-ResourceGroupName] <String> [<CommonParameters>]
`

the warning we got:

> WARNING: The Get-CosmosDbAccountConnectionString function does not currently work due to an issue with the Microsoft/DocumentDB provider. The connection strings will not be returned

what we can do?

**Comment by PlagueHO** [comment]
Hi @TimTang - what version of the Module are you using? Microsoft has fixed this issue with the Resource Provider and the latest version of the module, 3.5.0.426, will not show this warning and will successfully provide the connection strings.

Are you able to use the latest version?

**Comment by PlagueHO** [comment]
Hi @TimTang - is this issue resolved for you and can I close this off?

**Comment by TimTang** [comment]
@PlagueHO : please go ahead and close this one
