### ISSUE TITLE
400 Bad Request when using -Query with Get-CosmosDbDocument

### ISSUE THREAD

**Issue by mlee-bittitan** [PlagueHO/CosmosDB#319]
- [ ] Version of PowerShell you're using: 5.1.17763.771
- [ ] PowerShell host you're using: Console
- [ ] Operating system you're running: Windows 10
- [ ] Version of CosmosDB PowerShell Module you're using (use `Get-Module -Name CosmosDB`): 3.5.1.458

I understand that this seems like a duplicate issue from #22, but since that was quite a while back with a much earlier version of the CosmosDB module, and I'm getting what looks to be a very similar issue with the latest version of the module.

I'm following the guide [here](https://docs.microsoft.com/en-us/azure/cosmos-db/sql-query-getting-started), which creates a `Families` container with two entries.

The call which is failing is `Get-CosmosDbDocument -Context $cosmosDbContext -CollectionId "Families" -Query "SELECT * FROM Families"` with the error message:
```
Invoke-WebRequest : The remote server returned an error: (400) 
Bad Request.
At C:\Users\mlee\Documents\WindowsPowerShell\Modules\CosmosDB\3.5.
1.458\CosmosDB.psm1:5414 char:30
+ ...        $requestResult = Invoke-WebRequest 
@invokeWebRequestParameters
+                             
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (System.Net.HttpW 
   ebRequest:HttpWebRequest) [Invoke-WebRequest], WebException
    + FullyQualifiedErrorId : WebCmdletWebResponseException,Micro 
   soft.PowerShell.Commands.InvokeWebRequestCommand
```

I'm able to retrieve both entries from the container by running just `Get-CosmosDbDocument -Context $cosmosDbContext -CollectionId "Families"` which returns the below results, so the context does not seem to be the issue:
```
Id              Etag                                 ResourceId
--              ----                                 ----------
AndersenFamily  0c008198-0000-0800-0000-5df45a820000 0FlbALr7Q1...
WakefieldFamily 0c00da98-0000-0800-0000-5df45a8e0000 0FlbALr7Q1...
```

**Comment by PlagueHO** [comment]
Hi @mlee-bittitan ,

Unfortunately the CosmosDB REST APIs return 400 Bad Request for all sorts of reasons, so this could be a bug or something else.

Do you have a partition key on the collection? If so, are you specifying the ParitionKey parameter in the `Get-CosmosDbDocument` function?

**Comment by mlee-bittitan** [comment]
Thanks for the quick reply!

Yes the collection was created using a partition key - I don't think it's possible anymore (in the Azure portal UI at least) to create a new collection without specifying a partition key:

![image](https://user-images.githubusercontent.com/46809352/70858028-a11cc880-1f34-11ea-936f-435c4a456150.png)

I've tried using the `PartitionKey` parameter, but it does not seem to play nicely with the `Query` parameter. I can use the `PartitionKey` parameter to specify a specific item like `"AndersenFamily"`, but if I try to add a query to that call it doesn't change anything (which is quite expected I suppose):
```
Get-CosmosDbDocument -Context $cosmosDbContext -CollectionId Families -PartitionKey AndersenFamily -Query "SELECT * FROM Families"

Id             Etag                                 ResourceId               Timestamp              Uri
--             ----                                 ----------               ---------              ---
AndersenFamily 0c008198-0000-0800-0000-5df45a820000 0FlbALr7Q18BAAAAAAAAAA== 14/12/2019 11:44:02 AM dbs/0FlbAA==/colls/0FlbALr7Q18=...
```

**Comment by PlagueHO** [comment]
Hi @mlee-bittitan - you are correct, you can't create a collection without a partition through the portal any longer, but it is still possible via the REST APIs (although not recommended).

However, if you have created your collection with a partition key, and your query is essentially querying across partitions then you'll need to set the `QueryEnableCrossPartition` switch:

```powershell
Get-CosmosDbDocument -Context $cosmosDbContext -CollectionId "Families" -Query "SELECT * FROM Families" -QueryEnableCrossPartition
```

But, the thing to remember is that cross partition queries are expensive, so should be avoided if possible.

Give that a try and see if that solves the issue.

**Comment by mlee-bittitan** [comment]
Yes, with `QueryEnableCrossPartition` enabled, the query does exactly what I want!

Perhaps it would be good to include a separate section in the docs for querying across partitions, as it will probably come up more and more often now that a collection with partition is going to be the main use case for new users to Cosmos DB like myself.

**Comment by PlagueHO** [comment]
Thanks @mlee-bittitan - I'll update the docs with some examples of this.

**Comment by PlagueHO** [comment]
I've created a new issue to track this: #342
