### ISSUE TITLE
Add Support for Provisioning Container in Autopilot mode

### ISSUE THREAD

**Issue by PlagueHO** [PlagueHO/CosmosDB#321]
https://docs.microsoft.com/en-us/azure/cosmos-db/provision-throughput-autopilot

**Comment by DanielLarsenNZ** [comment]
Can't see an offer type in API docs yet. 

https://docs.microsoft.com/en-us/rest/api/cosmos-db/create-a-collection

Do we publish preview API docs?

**Comment by PlagueHO** [comment]
I'm not sure if we do publish preview API docs. If we can find out, and if the REST API's do support this then we should add the feature.

I'm updating the CI/CD pipeline to adopt a continuous delivery model that will allow us to release Preview modules to the PS Gallery (using @gaelcolas 's [Sampler](https://github.com/gaelcolas/Sampler/) project). This will allow features to get built and released more quickly. See #324

**Comment by PlagueHO** [comment]
Also, I suspect this REST API will also be affected by Auto-Pilot: https://docs.microsoft.com/en-us/rest/api/cosmos-db/offers

**Comment by PlagueHO** [comment]
Documentation is now available here: https://docs.microsoft.com/en-us/rest/api/cosmos-db/create-a-collection
