### ISSUE TITLE
New-CosmosDbDocument returns 400 Bad Request

### ISSUE THREAD

**Issue by Panzerbjrn** [PlagueHO/CosmosDB#339]
# Issue
- [5.1.18 ] Version of PowerShell you're using
- [Console Host ] PowerShell host you're using
- [Windows 10 ] Operating system you're running
- [3.6.1 ] Version of CosmosDB PowerShell Module 

I have created a database and collection fine with this context, and now wanted to add a document.
Using both the example here on GitHub:
`0..9 | Foreach-Object {
     $document = @"
 {
     "id": "$([Guid]::NewGuid().ToString())",
     "content": "Some string",
     "more": "Some other string"
 }
 "@}`
And a basic hashtable:
`$Document = @{id='91387b17-2f3b-4a2d-bb6f-d4b9362990f0'}`

I get the error:
`Invoke-WebRequest : The remote server returned an error: (400) Bad Request.`

When I turn on verbose, I get this in addition:
`
VERBOSE: Context does not contain any resource tokens.
VERBOSE: Creating authorization token: Method = 'Post', ResourceType = 'docs', ResourceId = 'dbs/SillyVendor/colls/SillyData', Date = '19/03/2020 23:18:18'.
VERBOSE: POST https://somedangurl.documents.azure.com/dbs/SillyVendor/colls/SillyData/docs with -1-byte payload
VERBOSE: {"code":"BadRequest","message":"Message: {\"Errors\":[\"The partition key supplied in x-ms-partitionkey header has fewer components than defined in the the collection.\"]}\r\nActivityId:
b751bf37-277e-4u79-ka3e-9574374d74ab, Request URI:
/apps/74gf6738-89o3-4ept-985e-077448fba767/services/7744e74a-2742-458f-a74d-07f974be5baa/partitions/5374b742-7774-4d74-b295-4e7748da14cd/replicas/174277747026137071p/, RequestStats: \r\nRequestStartTime:
2020-03-19T23:20:33.1437331Z, RequestEndTime: 2020-03-19T23:20:33.1637103Z,  Number of regions attempted:1\r\nResponseTime: 2020-03-19T23:20:33.1637103Z, StoreResult: StorePhysicalAddress:
rntbd://cdb-ms-prod-northus2-7474.documents.azure.com:14000/apps/333bb622-8743-744e-985e-077448fba767/services/7744e74a-2742-458f-a74d-07f974be5baa/partitions/5374b742-7774-4d74-b295-4e7748da14cd/replicas/1742774
77026137071p/, LSN: 3, GlobalCommittedLsn: 3, PartitionKeyRangeId: 0, IsValid: True, StatusCode: 400, SubStatusCode: 1001, RequestCharge: 0, ItemLSN: -1, SessionToken: 3, UsingLocalLSN: False,
TransportException: null, ResourceType: Document, OperationType: Create\r\n, SDK: Microsoft.Azure.Documents.Common/2.10.0"}
`
Since I created this database and collection from the guide, I would have thought I'd be able to add documents as well?

**Comment by PlagueHO** [comment]
Hi @Panzerbjrn - when you created the collection, did you specify partition keys? If you did, you need to either:
1. Enter values for the partition keys you specified, or
2. Enable the `QueryEnableCrossPartition` parameter to allow (expensive) cross partition queries.

But as you're probably getting the error when creating a new document then I'd suspect it is 1.

What is the partition key you set for the collection?

**Comment by Panzerbjrn** [comment]
I specified 'id' as the partition key, and that is also in the variable I'm passing...

**Comment by PlagueHO** [comment]
Hi @Panzerbjrn - ah right, I need to do some work to make the documentation clearer.

If you are creating documents in a Partitioned collection (which is pretty much _always_ the case now), then you need to include the `-PartitionKey` parameter. See: https://github.com/PlagueHO/CosmosDB#working-with-documents-in-a-partitioned-collection

When I originally created the module and wrote the docs, partitioning a collection wasn't mandatory (it pretty much is now).

**Comment by PlagueHO** [comment]
@Panzerbjrn - can you share the command you are running?

**Comment by Panzerbjrn** [comment]
Certaainly:
`New-CosmosDbDocument -Context $cosmosDbContext -CollectionId $collection -DocumentBody $Document -Verbose¬`

I also tried `New-CosmosDbDocument -Context $cosmosDbContext -CollectionId $collection -DocumentBody $Document -Verbose -Database $DBDatabase` but this gave the same error.

The variables were all used to create a new database and collection, using the code samples here on GitHub.
And if I do `Get-CosmosDbDocument -Context $cosmosDbContext -CollectionId $collection`, then I get the two records that I entered manually.

I also tried editing a record using
`$Doc1 =  Get-CosmosDbDocument -Context $cosmosDbContext -CollectionId $collection   | select -First 1`

`$newDocument = @"
{
    "id": "new_id_1234567890",
    "content": "New string",
    "more": "Another new string"
}
"@`

`Set-CosmosDbDocument -Context $cosmosDbContext -CollectionId $collection -Id $Doc1.id -DocumentBody $newDocument -Verbose`
But this gave the same error again.

**Comment by PlagueHO** [comment]
Hi @Panzerbjrn,

I suspect this is all to do with partition keys. Essentially is you create a collection with a partition key (which you should _always_ do), then you should be specifying a partition key value in every request you make to the CosmosDB Account. For example:

```powershell
New-CosmosDbCollection -Context $context -Id 'MyColl' -PartitionKey 'id' -OfferThroughput 400
$Document = '{ "id": "12345678", "content": "Somestuff" }'
New-CosmosDbDocument -Context $context -CollectionId 'MyColl' -DocumentBody $Document -PartitionKey '12345678' -Verbose
```

![image](https://user-images.githubusercontent.com/7589164/77201836-1ad6da80-6b52-11ea-9ffe-acbc8c480310.png)

If you query the collection then be sure to either specify the partition key or allow cross partition queries (recommend trying to avoid this as it is expensive and slow and may indicate a sub-optimal design).

```powershell
 Get-CosmosDbDocument -Context $context -CollectionId 'MyColl' -PartitionKey '12345678' -Id '12345678'
```

![image](https://user-images.githubusercontent.com/7589164/77201996-62f5fd00-6b52-11ea-9dce-401faa7e08e8.png)

I agree, I could do a better job with the docs here to indicate this. I plan to adjust the docs to show that partitioned collections are pretty much the default now so a PartitionKey should ALWAYS be used (really early on, when I first created this module PartitionKeys were optional).

**Comment by Panzerbjrn** [comment]
OK, thanks, I'll try that out later, 👍👍

**Comment by PlagueHO** [comment]
@Panzerbjrn - cool! Let me know how it goes. I'm about to update all the documentation to try and make this all a bit clearer and reduce focus on non-partitioned collections.

**Comment by Panzerbjrn** [comment]
*BOOM* And there it is...
Many thanks for your help.
If I find the time during the lockdown, between work and two small kids, I'll try to do a PR and add some Help to the CMDLets...

**Comment by PlagueHO** [comment]
Awesome! Thanks @Panzerbjrn !

All the cmdlet help is in the docs folder - I use PlatyPS to assemble it during build. So feel free to submit improvements to that. I did do some work on the docs yesterday, so they should be a little better/clearer now. Let me know what you think.

**Comment by Panzerbjrn** [comment]
I get the same error when trying Remove-CosmosDbDocument, and this is also fixed by adding -partitionkey...
