### ISSUE TITLE
403 forbidden

### ISSUE THREAD

**Issue by davejhahn** [PlagueHO/CosmosDB#353]
PowerShell 5.1.18362
ISE
Windows 10 Enterprise 10.0.18362 Build 18362
CosmosDB PowerShell module version 3.7.0

I ran into this issue with Cassandra and moved on to just use .NET, but I need to do some CosmosDB work and found myself back!

I'm running into a problem getting a 403 error when retrieving documents.    

I have "Allow access from all networks" enabled in Azure and can access it with .NET, so it's not a firewall restriction.  I can also pull collections using this PowerShell module CosmosDB, that works fine so it is clearly able to connect to the account and return results.

This works fine (getting the collections):
$cosmosDbContext = New-CosmosDbContext -Account 'MYACCOUNT' -Database 'MYDATABASE' -ResourceGroupName 'MYRG' -MasterKeyType 'PrimaryMasterKey'
$collections = Get-CosmosDbCollection -Context $cosmosDbContext

(Obviously with MYACCOUNT, MYDATABASE, and MYRG being replaced with my values).

This does not (getting the documents):
$cosmosDbContext = New-CosmosDbContext -Account 'MYACCOUNT' -Database 'MYDATABASE' -ResourceGroupName 'MYRG' -MasterKeyType 'PrimaryMasterKey'
$ResponseHeader = $null
$documents = Get-CosmosDbDocument -Context $cosmosDbContext -CollectionId 'MYCOLLECTION' -MaxItemCount 5 -ResponseHeader ([ref] $ResponseHeader)

When I execute the above, I get:
Invoke-WebRequest : The remote server returned an error: (403) Forbidden.

I would really love to use this module, writing .NET adds another layer of complexity in our pipelines.  

For what it's worth, I tried this on my home machine (versus work) without any VPN restrictions, so it is not a local firewall issue either.

The above was pretty much copy and paste examples, so I am not doing anything weird as far as I know.  I didn't find this error coming up with anyone else so I am a little stumped.

Thanks!

Dave

**Comment by PlagueHO** [comment]
Hi @davejhahn - 

Which of the two commands `New-CosmosDbContext` and `Get-CosmosDbContext` does the 403 occur on?

You're completely right - the 403 will occurs when there is a firewall in place that blocks it OR if the master key supplied is incorrect.

I wonder if for some reason when the `New-CosmosDbContext` cmdlet is getting the MasterKey from your CosmosDB account it is unable to do so. Can you try manually assigning the CosmosDB key to the context by running something like this:

```powershell
$primaryKey = ConvertTo-SecureString -String '.... get this from the Azure Portal ....' -AsPlainText -Force
$cosmosDbContext = New-CosmosDbContext -Account 'MYACCOUNT' -Database 'MYDATABASE' -Key $primaryKey
```

Does that work?

Also, have you put the CosmosDB in a VNET using either Service Endpoint or Private Link?

Something else I noted:
You don't need to specify the `-MasterKeyType 'PrimaryMasterKey'` in the commands as this is the default value. I don't think this is the cause of the problem but it'll shorten your code.

**Comment by davejhahn** [comment]
@PlagueHO 403 happens when I use the New-CosmosDbContext context with Get-CosmosDbDocument.  Not sure about Get-CosmosDbContext, it doesn't seem to be a command (unless you meant Get-CosmosDbDocument).   It does not fail on New-CosmosDbContext, that is fine, it's just the Get-CosmosDbDocument.

I really don't see firewall being an issue--it is opened up to public on Azure and I can successfully get the collections using Get-CosmosDbCollection with the same dbcontext.  I also get the same results on my work laptop and personal laptop. 

And regarding VNET/Private links, no not using either.

I was curious about accessing the documents through the collection, which I can retrieve, but when I look at $collections[1].Documents it shows docs/  - so I'm not sure what that is or if it helps.

Let me know if there is anything else that would be useful to check

Thanks!

Dave

**Comment by PlagueHO** [comment]
Hi @davejhahn - my bad, sorry, I meant the `New-CosmosDbDocument` and `Get-CosmosDbDocument` functions.

So, do you get a 403 when adding the document to the collection or just retrieving one?

**Comment by davejhahn** [comment]
Sorry for the delay in responding--I tried inserting a new doc with New-CosmosDBDocument and I also get  403 Forbidden.

**Comment by PlagueHO** [comment]
Hi @davejhahn - this would usually indicate the master key that is being used is not valid.

Have you tried getting the master key straight from the portal and pasting it into these commands to generate the context:

```powershell
$primaryKey = ConvertTo-SecureString -String '.... get this from the Azure Portal ....' -AsPlainText -Force
$cosmosDbContext = New-CosmosDbContext -Account 'MYACCOUNT' -Database 'MYDATABASE' -Key $primaryKey
```

And then run the `New-CosmosDBDocument` command. If this works then it will indicate that there is some problem in the code that is getting the master key from the Azure Portal.

One final thing to confirm (unlikely): You aren't using a resource key rather than a master key? I doubt this as it is pretty rare that people use resource keys and your code definitely doesn't show generating a resource key.

**Comment by davejhahn** [comment]
Yes, I tried that and it is the same behavior.  I apologize, I thought I mentioned that in my previous reply.  I can query the collection, get the names, etc... either way, so it is clearly able to access it.

**Comment by PlagueHO** [comment]
No worries. That is really strange that you can query the collection but not add documents to it. I've not seen that before.

If you add the `-Verbose` parameter to the `New-ComsosDbDocument` command it will give you a little bit more detail on the exact error being returned by CosmosDB. Does that give you any more information?

I would have suggested that possibly this is a problem with not specifying a partition key, but that usually returns a 400 bad request.

**Comment by davejhahn** [comment]
Yes, the verbose is providing the following (scrubbed to remove identifiable information):

VERBOSE: Context does not contain any resource tokens.
VERBOSE: Creating authorization token: Method = 'Post', ResourceType = 'docs', ResourceId = 'dbs/xxxxx/colls/Test', Date = '5/8/2020 8:10:01 PM'.
VERBOSE: POST https://xxxxx.documents.azure.com/dbs/xxxxx/colls/Test/docs with -1-byte payload
VERBOSE: {"code":"Forbidden","message":"Sql api is not supported for this database account\r\nActivityId: xxxxxx-a374-4879-bfdf-xxxxxxx, Microsoft.Azure.Documents.Common/2

Not sure if this is a generic message, but why is it trying to use Sql api?  Am I trying to use this module for something it wasn't intended for?  

The API type I have set for this CosmosDB instance is MongoDB. If I do an az cosmosdb show, it definitely shows it is MongoDB: "kind": "MongoDB",

**Comment by PlagueHO** [comment]
Hi @davejhahn - oh right! I see the problem now.

Cosmos DB can operate in many different modes. SQL DB API is one of the modes and is the only one that exposes this REST API. MongoDB is another mode, but it doesn't expose the REST APIs - you must instead use native MongoDB tools to work against the database.

See this page for info: https://docs.microsoft.com/en-us/rest/api/cosmos-db/

For details on how to interact with the Cosmos DB APIs for Mongo DB, check out this page: https://docs.microsoft.com/en-us/azure/cosmos-db/mongodb-introduction

So, essentially you've got two options:
1. When you create your Cosmos DB account, set it to use SQL DB APIs.
2. Use the Mongo DB tools/SDKs to interact with it.

I'm not sure if there are native PowerShell Mongo DB modules (I think there are), but there is a command line binary for interacting with MongoDB.

**Comment by davejhahn** [comment]
@PlagueHO ok thanks, totally sorry for making you go down this rabbit hole.  It never occurred to me that this was the issue.   Thanks!  Dave

**Comment by PlagueHO** [comment]
@davejhahn - no worries at all! I think this just shows a gap in my documentation! So I better update it :grin:. I'll keep this open until I do.

**Comment by davejhahn** [comment]
Closing since the API version I was using is not supported.
