### ISSUE TITLE
Allow passing https:// and :port through $URL

### ISSUE THREAD

**Issue by tamusjroyce** [PlagueHO/CosmosDB#381]
# Issue
When using https://mycompaniesabbr.documents.azure.com:443/ I get an exception when trying to get a database context

# Conclusion

$URL should match what is shown in portal or cosmos emulator

![image](https://user-images.githubusercontent.com/6413071/83318374-476a3b00-a202-11ea-8267-4e94d55cbcda.png)

# Solution

```
diff --git a/source/Public/utils/New-CosmosDbContext.ps1 b/source/Public/utils/New-CosmosDbContext.ps1
index af5514d..40d6b84 100644
--- a/source/Public/utils/New-CosmosDbContext.ps1
+++ b/source/Public/utils/New-CosmosDbContext.ps1
@@ -87,7 +87,15 @@ function New-CosmosDbContext
                     -Force
             }

-            $BaseUri = [uri]::new(('https://{0}:{1}' -f $URI, $Port))
+            if ($URI -like '*:*' -And $URI -like '*://*') {
+                $BaseUri = [uri]::new($URI)
+            } else if ($URI -like '*:*') {
+                $BaseUri = [uri]::new(('https://{0}' -f $URI))
+            } else if ($URI -like '*://*') {
+                $BaseUri = [uri]::new(('{0}:{1}' -f $URI, $Port))
+            } else {
+                $BaseUri = [uri]::new(('https://{0}:{1}' -f $URI, $Port))
+            }
         }

         'AzureAccount'
```
Sorry for the git diff instead of a PR. This is missing a unit test and hasn't been ran. Wouldn't be surprised if a a syntax error is hiding in there somewhere.

Before submitting your issue for the CosmosDB project, please take a moment to
provide the following details:

- [ 5 ] Version of PowerShell you're using
- [ ISE ] PowerShell host you're using (eg. Console Host, ISE, Visual Studio)
- [ Windows 10 ] Operating system you're running
- [ 4.1.0 ] Version of CosmosDB PowerShell Module you're using (use `Get-Module -Name CosmosDB`)

Thanks for contributing your feedback and support! You can optionally submit a
Pull Request against this project, if you have a fix you'd like to share.

**Comment by PlagueHO** [comment]
Hi @tamusjroyce - are you trying to use the module to connect to a CosmosDB emulator? If so, see this method of creating the context:
https://github.com/PlagueHO/CosmosDB#create-a-context-for-a-cosmos-db-emulator

Apologies if I've misunderstood the issue.

**Comment by tamusjroyce** [comment]
Original is

`$cosmosDbContext = New-CosmosDbContext -Emulator -Database 'MyDatabase' -URI 'myemulator.local' -Key $primaryKey
`

From the screenshot put what is shown into $URL

$sourceUrl = 'https://localhost:8081' #URL shown in emulator (what my DevOps guys will know to enter)
$useEmulator = $true
$sourceDatabaseName = 'yup' # favorite King of the Hill quote (intro fence)

```
$useEmulator = $false
if ((Read-Host -Prompt "Use Azure Cosmos Emulator? [y/N]") -like "y") {
    $useEmulator = $true
    $cosmosEmulatorPath = Get-Package | Where-Object{ $_.Name -like "Azure Cosmos DB Emulator" } | % { $_.Source }
    if ([string]::IsNullOrEmpty($cosmosEmulatorPath)) {
        Start "https://aka.ms/cosmosdb-emulator"
    }

    while ([string]::IsNullOrEmpty($cosmosEmulatorPath)) {
        if ((Read-Host -Prompt "Has Azure Cosmos Emulator been downloaded and installed? [Press enter to check or y to skip]") -like "y") {
            break
        }
        $cosmosEmulatorPath = Get-Package | Where-Object{ $_.Name -like "*Cosmos*" } | % { $_.Source }
    }

    Start -FilePath (Join-Path -Path $cosmosEmulatorPath -ChildPath "Microsoft.Azure.Cosmos.Emulator.exe")
    Start "https://localhost:8081/_explorer/index.html"
    Write-Output "CosmosDB should be open with the key showing"
} else {
    Start "https://portal.azure.com/#blade/HubsExtension/BrowseResource/resourceType/Microsoft.DocumentDb%2FdatabaseAccounts"
    Write-Output "Please navigate to the CosmosDB resource and open Keys under settings and select Read-only keys"
}

$sourceUrl = Read-Host -Prompt 'Enter source the Cosmos URL'
$sourceKey = Read-Host -Prompt 'Enter the  source Cosmos key'
$sourceDatabaseName = Read-Host -Prompt 'Enter the source database name'
$sourceContainerName = Read-Host -Prompt 'Enter the source container name'

$backoffPolicy = New-CosmosDbBackoffPolicy -MaxRetries 20
$primarySourceKey = ConvertTo-SecureString -String $sourceKey.Trim() -AsPlainText -Force
if ($useEmulator -eq $true) {
    $sourceCosmosDbContext = New-CosmosDbContext -Emulator -Database $sourceDatabaseName -URI $sourceUrl -Key $primarySourceKey -BackoffPolicy $backoffPolicy
} else {
    $sourceCosmosDbContext = New-CosmosDbContext -Database $sourceDatabaseName -URI $sourceUrl -Key $primarySourceKey -BackoffPolicy $backoffPolicy
}
```
This breaks. The DevOps guy's won't know to leave the https:// off or put the port in separately.
And this could be typed as many as 20 times during a scheduled window (to make changes through all our collections)

Try it again using Azure
$sourceUrl = 'https://mycompaniesabbr.documents.azure.com:443/' #URL shown in emulator (what my DevOps guys will know to enter)
$useEmulator = $false
$sourceDatabaseName = 'CompaniesDatabase' # favorite King of the Hill quote (intro fence)

Why can't URL shown in the URI of the screenshot be usable?

p.s. Also, Cosmos Clone uses the URL in the screenshot to perform a copy - however that can't be customized or put into a script like your tool

Feel free to close this out as a wont-do. I can work around it.
This tool is so slick and helpful. Really glad I came across it!

**Comment by tamusjroyce** [comment]
Feel free to close this out as a wont-do. I can work around it.
This tool is so slick and helpful. Really glad I came across it!

**Comment by PlagueHO** [comment]
Hi @tamusjroyce - ah, I see I think. So what you'd like to be able to do is:

```powershell
$cosmosDbContext = New-CosmosDbContext -Emulator -Database 'MyDatabase' -URI 'https://localhost:8081' -Key $primaryKey
```

And have that work OK - is that correct? I think I can do this (and it does make sense).
