### ISSUE TITLE
Missing a letter in readme

### ISSUE THREAD

**Issue by GeoffreyDu** [PlagueHO/CosmosDB#396]
# Issue
Hi,

In the README in working with databases section at line :
```
New-CosmosDbDatabase -Context $cosmosDbContext -Id 'MyDatabase' -OfferThrougput 1200
```
It's missing a "h" in the word OfferThroughput

Before submitting your issue for the CosmosDB project, please take a moment to
provide the following details:

- [ ] Version of PowerShell you're using
- [ ] PowerShell host you're using (eg. Console Host, ISE, Visual Studio)
- [ ] Operating system you're running
- [ ] Version of CosmosDB PowerShell Module you're using (use `Get-Module -Name CosmosDB`)

Thanks for contributing your feedback and support! You can optionally submit a
Pull Request against this project, if you have a fix you'd like to share.

**Comment by PlagueHO** [comment]
Hi @GeoffreyDu - wow, thanks for raising this. I'll fix and add the misspelled one as an alias so that it doesn't break any existing code.

**Comment by PlagueHO** [comment]
Doh - misread - I thought the misspelling was in the cmdlet. Will fix :grin:

**Comment by GeoffreyDu** [comment]
No problem 👍 thank you for the fast answer
