### ISSUE TITLE
Add support for creating Indexing Policy on Collections

### ISSUE THREAD

**Issue by EwanNoble** [PlagueHO/CosmosDB#42]
https://docs.microsoft.com/en-us/rest/api/documentdb/collections#indexing-policy

https://docs.microsoft.com/en-us/rest/api/documentdb/create-a-collection

**Comment by PlagueHO** [comment]
Hi @EwanNoble - thank you for raising this! This is something I meant to add but it slipped my mind - so I'll get onto it. Thank you for reminding me :grin:

**Comment by PlagueHO** [comment]
This is in progress now and should be complete with documentation and tests later on today/tomorrow. I've added a bunch of new utility functions that help assemble the Index Policy object which can be passed in while creating the collection.

**Comment by PlagueHO** [comment]
Ok, all done! You can find the documentation and short example (based on the Microsoft docs) here: https://github.com/PlagueHO/CosmosDB#creating-a-collection-with-a-custom-indexing-policy

I've published this to PS Gallery as 2.0.3: https://www.powershellgallery.com/packages/CosmosDB/2.0.3.190

I did include another change in this release: https://github.com/PlagueHO/CosmosDB/issues/43

I changed "Connection" to "Context" for parameters and functions to align more closely to the naming used by the Microsoft Azure PowerShell team (e.g. New-AzureRMApiManagementContext). But I used aliases to ensure that the old function names and parameter names would still work. But please let me know if this breaks anything for you.

**Comment by EwanNoble** [comment]
Many thanks!

**Comment by noskcajmas** [comment]
Wonderful, Thanks PlagueHO!!

**Comment by PlagueHO** [comment]
A pleasure! Cheers!
