### ISSUE TITLE
Error 404 with get and set cosmosdbdocument

### ISSUE THREAD

**Issue by gekkegerrit101** [PlagueHO/CosmosDB#429]
# Issue

- Powershell version 5.1.19041.1023
- Using Visual Studio
- Using Windows 10
- Using version 4.5.0 of the CosmosDB module

I'm getting an error 404 when I try to get or set an exisiting CosmosDB document. The get command I'm submitting:

Get-CosmosDbDocument -Context $cosmosDbContext -CollectionId $CollectionId -Id "065a2cbf-xxxx-xxxx-xxxx-xxxxxxxxxxxx" -PartitionKey 'id'

Set-CosmosDbDocument -Context $cosmosDbContext -CollectionId $CollectionId -Id "065a2cbf-xxxx-xxxx-xxxx-xxxxxxxxxxxx" -DocumentBody $newDocument -PartitionKey "id"

![image](https://user-images.githubusercontent.com/15068745/128707711-89d80e25-5fd3-4701-afb3-f831ac54dc5c.png)

Without supplying the PartitionKey value I get an error 400, but I believe that's to be expected. Am I missing something here?

**Comment by PlagueHO** [comment]
Hi @gekkegerrit101 ,

You need to specify the actual partition key value in the '-PartitionKey' parameter. E.g. the guid value from the Id in the document.

Does that fix the problem?

**Comment by gekkegerrit101** [comment]
Yes that works, thank you very much!
