### ISSUE TITLE
Feature request: Add support for partial updates to document

### ISSUE THREAD

**Issue by Szeraax** [PlagueHO/CosmosDB#448]
Announced today, Cosmos has partial update support: https://devblogs.microsoft.com/cosmosdb/partial-document-update-ga/

**Comment by PlagueHO** [comment]
Hi @Szeraax - I just saw that too. I'm hoping the REST API's will be updated with this feature as well: https://docs.microsoft.com/en-us/rest/api/cosmos-db/

**Comment by Szeraax** [comment]
Closing for now at least.

**Comment by Szeraax** [comment]
Hey @PlagueHO, am I reading this right that we now have PATCH capability in the API? 

https://learn.microsoft.com/en-us/rest/api/cosmos-db/patch-a-document

**Comment by Szeraax** [comment]
Looks like it is supported now and it requires that you use the Patch method with an array of operations. I think the best way to go about implementing this will be to add a PatchOperation type in our module class and then add a `Update-CosmosDbDocument` cmdlet. `Update-CosmosDbDocument` would have an optional `PartitionKey` string param, an optional conditional filter (probably just use `-Filter` for the param name), and would require an array of the `[PatchOperation]` objects.

Here is the other document that is helpful to look at: https://learn.microsoft.com/en-us/azure/cosmos-db/partial-document-update

Any guidance on my approach? Cool if I take a first pass at a PR or would you like me to do this in a different way?
