### ISSUE TITLE
New-CosmosDbDocument fails on partitioned collections

### ISSUE THREAD

**Issue by Kodeshio** [PlagueHO/CosmosDB#48]
Version of PowerShell: 5.1.1
Running in: VSTS, ISE

New-CosmosDbDocument fails with a 400 error when the collection is partitioned. This looks to be down to the x-ms-documentdb-partitionkey header missing.

Example code:

```
    $document = @"
{
    `"id`": `"$([Guid]::NewGuid().ToString())`",
    `"content`": `"Some string`",
    `"more`": `"Some other string`"
}
"@

    $cosmosDbConnection = New-CosmosDbConnection -Emulator -Database 'Database'
    
    New-CosmosDbDatabase -Connection $cosmosDbConnection -Id 'Database'

    New-CosmosDbCollection -Connection $cosmosDbConnection -Id 'Collection' -OfferThroughput 2500 -PartitionKey "id"

    New-CosmosDbDocument -Connection $cosmosDbConnection -CollectionId 'Collection' -DocumentBody $document
```

If you remove the ```-PartitionKey "id"``` from the above it works fine. I have tested a local change with PartitionKey as a parameter to New-CosmosDbDocument, doing something like:

```
	if ($PSBoundParameters.ContainsKey('PartitionKey'))
    {
        $headers += @{
            'x-ms-documentdb-partitionkey' = '["' + $PartitionKey + '"]'
        }
        $null = $PSBoundParameters.Remove('PartitionKey')
    }
```

And that all seems OK, I haven't put in a PR as I'm unsure what approach you'd prefer :)

**Comment by PlagueHO** [comment]
Good catch @Kodeshio - and thank you for the offer of a PR! When I was looking over the code I found a number of other places I hadn't managed the PartitionKey correctly so I did a bunch of other work on this at the same time.

Anyway, the [new version (2.0.4)](https://www.powershellgallery.com/packages/CosmosDB/2.0.4.202) has been released to the PS Gallery including your suggested fix of adding the PartitionKey parameter to the `New-CosmosDbDocument` function. I also made some other changes:

- Fixed bug in `Get-CosmosDbDocument` when looking up a document in
  a partitioned collection by adding a `PartitionKey` parameter.
- Added `Upsert` parameter to `New-CosmosDbDocument` to enable updating
  a document if it exists.
- Fixed bug in `New-CosmosDbDocument` when adding document to
  a partitioned collection but no partition key is specified - See
  [Issue #48](https://github.com/PlagueHO/CosmosDB/issues/48).
- Fixed bug in `Set-CosmosDbDocument` when updating a document in
  a partitioned collection.
- Fixed bug in `Remove-CosmosDbDocument` when deleting a document in
  a partitioned collection.
- Added check to `New-CosmosDbCollection` to ensure `PartitionKey`
  parameter is passed if `OfferThroughput` is greater than 10000.

I do intend on implementing a full suite of integration tests at some point that will actually create a CosmosDB in my Azure account and run a full suite of E2E tests on this, but I haven't had the time yet.

Anyway, I'm definitely happy to accept PR's on this project :grin:
