### ISSUE TITLE
Error 401 When Creating Collections in Databases

### ISSUE THREAD

**Issue by PlagueHO** [PlagueHO/CosmosDB#84]
I have issues when the database name is capital
![image](https://user-images.githubusercontent.com/7589164/38772640-f8c78ae6-408f-11e8-9ca1-97ec01a24687.png)

If I run that script above it will correctly query the collection
If I make a 2nd database with Example it will 401 error

![image](https://user-images.githubusercontent.com/7589164/38772651-3ec6b9cc-4090-11e8-8f87-798971e6d9f1.png)

![image](https://user-images.githubusercontent.com/7589164/38772652-47a807a8-4090-11e8-9c7d-d295b63b5992.png)

The creation Error is below :

![image](https://user-images.githubusercontent.com/7589164/38772661-56736818-4090-11e8-9f0a-481463a1db39.png)

Code for that is :
![image](https://user-images.githubusercontent.com/7589164/38772664-63bdc8ba-4090-11e8-888c-87a1471e2c9d.png)

PSVersion 5.1.16299.251 , I get same error on both 2.08.350 and 2.0.7.288

**Comment by PlagueHO** [comment]
I promise to get onto this one this week -I've begun adding some functional/integration tests so that I can improve the general quality of the module (as per #51 ) and will hopefully identify and fix your issue at the same time. Thanks for your patience!

**Comment by ArifvTim** [comment]
Hey , this isn't a bug anymore with the newest version. The fix you included for the other unauthorized issues solved this as well!

**Comment by PlagueHO** [comment]
Doh! Missed this - I'll close this issue as it is no longer an issue.
